In [2]:
import numpy as np
mtrx=np.arange(64).reshape(8,8)
print(mtrx)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [3]:
mtrx=np.matrix([[1,2,3],[1,1,1]])
print(mtrx)

[[1 2 3]
 [1 1 1]]


In [4]:
arr=np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


python deals with numpy arrays as normal arrays

In [5]:
def reverse_arr(arr, copy=True):
    if copy:
        arr=arr.copy()
    mid = len(arr) //2
    for i in range(mid):
        arr[i],arr[-i-1] = arr[-i-1],arr[i]   
    return arr

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
reversed=reverse_arr(arr)

In [8]:
reversed

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:

prices = np.full(100, fill_value=np.nan)
prices[[0,25,60,-1]]=[80., 30., 75., 50.,]

In [10]:
prices

array([80., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 30.,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, 75., nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, 50.])